[package]
name = "ragit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rag"
path = "src/main.rs"

[dependencies]
clearscreen = "3.0.0"
flate2 = "1.0.34"
h_time = "0.1.0"
json = "0.12.4"
lazy_static = "1.5.0"
ragit-api = { path = "./crates/api", version = "0.1.0" }
ragit-fs = { path = "./crates/fs", version = "0.1.0" }
rand = "0.8.5"
regex = "1.10.6"
rust-stemmers = "1.2.0"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.128"
sha3 = "0.10.8"
tera = "*"
tokio = { version = "*", features = ["full"] }
