[package]
name = "ragit"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "git-like rag pipeline"

[[bin]]
name = "rag"
path = "src/main.rs"

[dependencies]
clearscreen = "3.0.0"
flate2 = "1.0.34"
h_time = "0.1.0"
image = "0.25.4"
json = "0.12.4"
lazy_static = "1.5.0"
ragit-api = { path = "./crates/api", version = "0.1.0" }
ragit-fs = { path = "./crates/fs", version = "0.1.0" }
rand = "0.8.5"
regex = "1.10.6"
rust-stemmers = "1.2.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sha3 = "0.10.8"
tera = "1.20.0"
tokio = { version = "1.40.0", features = ["full"] }
