[package]
name = "ragit-api"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "api utilities for ragit"

[dependencies]
async-std = "1.13.0"
base64 = "0.22.1"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
futures = "0.3.30"
image = "0.25.4"
json = "0.12.4"
ragit-fs = { path = "../fs", version = "0.1.1" }
rand = "0.8.5"
regex = "1.11.1"
reqwest = "0.12.9"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tera = "1.20.0"
tokio = { version = "1.41.0", features = ["full"] }
