[package]
name = "ragit-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-fs = { path = "../fs", version = "0.1.0" }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
warp = "0.3.7"
