[package]
name = "ragit-server"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "poc server implementation of ragit"

[dependencies]
ragit = { path = "../..", version = "0.2.1" }
ragit-fs = { path = "../fs", version = "0.2.1" }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
warp = "0.3.7"
